version: '3.8'

services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ~/mongodb/data/db/tspa:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tspa
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "tspa-rs" ]
  mongo-setup:
    image: mongo:7.0-jammy
    depends_on:
      - mongodb
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh --host localhost:27017 --eval \"rs.initiate({ '_id': 'tspa-rs', 'version': 1, 'members': [{ '_id': 1, 'host': 'localhost:27017' }] }, { force: true })\" && echo 'Done with replica-set initialization'" ]
