name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - name: Install dependencies
        run: yarn run clean:install:ci
      - name: Code linting
        run: yarn run lint:ci
